# SPDX-License-Identifier: GPL-3.0-or-later

version: v1
profile: fastapi
runner: netdata-prometheus-source-registry-v1
upstreams:
  fastapi_instrumentator:
    repository: trallnag/prometheus-fastapi-instrumentator
    commit: 2f841527277a21ac9ea622a9f923a5f9078234c4
    paths:
      - src/prometheus_fastapi_instrumentator/metrics.py
  prometheus_client_python:
    repository: prometheus/client_python
    commit: f417f6ea8f058165a1934e368fed245e91aafc14
    paths:
      - prometheus_client/metrics.py
