# SPDX-License-Identifier: GPL-3.0-or-later

version: v1
profile: ceph
runner: netdata-prometheus-source-registry-v1
upstreams:
  ceph_nvmeof:
    repository: ceph/ceph-nvmeof
    commit: c79b6f44bd2288f7ec5c48e3cc47f6e566573d3f
    paths:
      - control/prometheus.py
      - pyproject.toml
  ceph_reef:
    repository: ceph/ceph
    commit: efac5a54607c13fa50d4822e50242b86e6e446df
    paths:
      - src/blk/kernel/KernelDevice.cc
      - src/client/Client.cc
      - src/common/ceph_context.cc
      - src/common/Finisher.cc
      - src/common/Finisher.h
      - src/common/options/ceph-exporter.yaml.in
      - src/common/options/cephfs-mirror.yaml.in
      - src/common/options/mgr.yaml.in
      - src/common/options/rbd-mirror.yaml.in
      - src/common/perf_counters.cc
      - src/common/perf_counters.h
      - src/common/PriorityCache.cc
      - src/common/Throttle.cc
      - src/common/TrackedOp.h
      - src/exporter/DaemonMetricCollector.cc
      - src/exporter/util.cc
      - src/include/mempool.h
      - src/kv/RocksDBStore.cc
      - src/libcephsqlite.cc
      - src/librbd/cache/pwl/AbstractWriteLog.cc
      - src/librbd/ImageCtx.cc
      - src/mds/MDCache.cc
      - src/mds/MDLog.cc
      - src/mds/MDSRank.cc
      - src/mds/MetricAggregator.cc
      - src/mds/OpenFileTable.cc
      - src/mds/PurgeQueue.cc
      - src/mds/Server.cc
      - src/mds/SessionMap.cc
      - src/messages/MMgrReport.h
      - src/mgr/DaemonServer.cc
      - src/mgr/mgr_perf_counters.cc
      - src/mon/Monitor.cc
      - src/mon/MonitorDBStore.h
      - src/mon/OSDMonitor.cc
      - src/mon/Paxos.cc
      - src/msg/async/dpdk/DPDK.cc
      - src/msg/async/dpdk/DPDK.h
      - src/msg/async/dpdk/IP.cc
      - src/msg/async/rdma/RDMAStack.cc
      - src/msg/async/Stack.h
      - src/os/bluestore/BlueFS.cc
      - src/os/bluestore/BlueStore.cc
      - src/os/kstore/KStore.cc
      - src/osd/osd_perf_counters.cc
      - src/osd/scheduler/mClockScheduler.cc
      - src/osdc/ObjectCacher.cc
      - src/osdc/Objecter.cc
      - src/pybind/mgr/mgr_module.py
      - src/pybind/mgr/prometheus/module.py
      - src/rgw/driver/rados/rgw_sync_counters.cc
      - src/rgw/rgw_dmclock_scheduler_ctx.cc
      - src/rgw/rgw_perf_counters.cc
      - src/SimpleRADOSStriper.cc
      - src/tools/cephfs_mirror/FSMirror.cc
      - src/tools/cephfs_mirror/Mirror.cc
      - src/tools/cephfs_mirror/PeerReplayer.cc
      - src/tools/rbd_mirror/image_replayer/journal/Replayer.cc
      - src/tools/rbd_mirror/image_replayer/snapshot/Replayer.cc
      - src/tools/rbd_mirror/main.cc
      - src/tools/rbd_mirror/Mirror.cc
  ceph_squid:
    repository: ceph/ceph
    commit: abc7aa7f2701e5d46878fd5e6bb7e2955f1a395a
    paths:
      - src/blk/kernel/KernelDevice.cc
      - src/client/Client.cc
      - src/common/ceph_context.cc
      - src/common/Finisher.cc
      - src/common/Finisher.h
      - src/common/options/ceph-exporter.yaml.in
      - src/common/options/cephfs-mirror.yaml.in
      - src/common/options/mgr.yaml.in
      - src/common/options/rbd-mirror.yaml.in
      - src/common/perf_counters.cc
      - src/common/perf_counters.h
      - src/common/PriorityCache.cc
      - src/common/Throttle.cc
      - src/common/TrackedOp.h
      - src/exporter/DaemonMetricCollector.cc
      - src/exporter/util.cc
      - src/include/mempool.h
      - src/kv/RocksDBStore.cc
      - src/libcephsqlite.cc
      - src/librbd/cache/pwl/AbstractWriteLog.cc
      - src/librbd/ImageCtx.cc
      - src/mds/MDCache.cc
      - src/mds/MDLog.cc
      - src/mds/MDSRank.cc
      - src/mds/MetricAggregator.cc
      - src/mds/OpenFileTable.cc
      - src/mds/PurgeQueue.cc
      - src/mds/Server.cc
      - src/mds/SessionMap.cc
      - src/messages/MMgrReport.h
      - src/mgr/DaemonServer.cc
      - src/mgr/mgr_perf_counters.cc
      - src/mon/Monitor.cc
      - src/mon/MonitorDBStore.h
      - src/mon/OSDMonitor.cc
      - src/mon/Paxos.cc
      - src/msg/async/dpdk/DPDK.cc
      - src/msg/async/dpdk/DPDK.h
      - src/msg/async/dpdk/IP.cc
      - src/msg/async/rdma/RDMAStack.cc
      - src/msg/async/Stack.h
      - src/os/bluestore/BlueFS.cc
      - src/os/bluestore/BlueStore.cc
      - src/os/kstore/KStore.cc
      - src/osd/osd_perf_counters.cc
      - src/osd/scheduler/mClockScheduler.cc
      - src/osd/scrubber/osd_scrub.cc
      - src/osd/scrubber/osd_scrub.h
      - src/osdc/ObjectCacher.cc
      - src/osdc/Objecter.cc
      - src/pybind/mgr/mgr_module.py
      - src/pybind/mgr/prometheus/module.py
      - src/rgw/driver/rados/rgw_sync_counters.cc
      - src/rgw/rgw_dmclock_scheduler_ctx.cc
      - src/rgw/rgw_perf_counters.cc
      - src/SimpleRADOSStriper.cc
      - src/tools/cephfs_mirror/FSMirror.cc
      - src/tools/cephfs_mirror/Mirror.cc
      - src/tools/cephfs_mirror/PeerReplayer.cc
      - src/tools/rbd_mirror/image_replayer/journal/Replayer.cc
      - src/tools/rbd_mirror/image_replayer/snapshot/Replayer.cc
      - src/tools/rbd_mirror/main.cc
      - src/tools/rbd_mirror/Mirror.cc
  prometheus_client_python:
    repository: prometheus/client_python
    commit: 2dcd17efd0ce2f0a1ad15cb3c150ffcdc42ced65
    paths:
      - prometheus_client/exposition.py
      - prometheus_client/metrics_core.py
  ceph_tentacle:
    repository: ceph/ceph
    commit: 0fcffee29411e3a38036764817b6e1afc59741cc
    paths:
      - src/blk/kernel/KernelDevice.cc
      - src/client/Client.cc
      - src/common/ceph_context.cc
      - src/common/Finisher.cc
      - src/common/options/ceph-exporter.yaml.in
      - src/common/options/cephfs-mirror.yaml.in
      - src/common/options/mgr.yaml.in
      - src/common/options/rbd-mirror.yaml.in
      - src/common/perf_counters.cc
      - src/common/perf_counters.h
      - src/common/PriorityCache.cc
      - src/common/Throttle.cc
      - src/common/TrackedOp.h
      - src/exporter/DaemonMetricCollector.cc
      - src/exporter/util.cc
      - src/extblkdev/fcm/ExtBlkDevPluginFcm.cc
      - src/include/mempool.h
      - src/kv/rocksdb_cache/BinnedLRUCache.cc
      - src/kv/rocksdb_cache/BinnedLRUCache.h
      - src/kv/RocksDBStore.cc
      - src/libcephsqlite.cc
      - src/librbd/cache/pwl/AbstractWriteLog.cc
      - src/librbd/ImageCtx.cc
      - src/mds/MDCache.cc
      - src/mds/MDLog.cc
      - src/mds/MDSRank.cc
      - src/mds/MetricAggregator.cc
      - src/mds/OpenFileTable.cc
      - src/mds/PurgeQueue.cc
      - src/mds/Server.cc
      - src/mds/SessionMap.cc
      - src/messages/MMgrReport.h
      - src/mgr/DaemonServer.cc
      - src/mgr/mgr_perf_counters.cc
      - src/mon/Monitor.cc
      - src/mon/MonitorDBStore.h
      - src/mon/OSDMonitor.cc
      - src/mon/Paxos.cc
      - src/msg/async/dpdk/DPDK.cc
      - src/msg/async/dpdk/DPDK.h
      - src/msg/async/dpdk/IP.cc
      - src/msg/async/rdma/RDMAStack.cc
      - src/msg/async/Stack.h
      - src/os/bluestore/BlueFS.cc
      - src/os/bluestore/BlueStore.cc
      - src/os/kstore/KStore.cc
      - src/osd/osd_perf_counters.cc
      - src/osd/scheduler/mClockScheduler.cc
      - src/osd/scrubber/osd_scrub.cc
      - src/osd/scrubber/osd_scrub.h
      - src/osdc/ObjectCacher.cc
      - src/osdc/Objecter.cc
      - src/pybind/mgr/mgr_module.py
      - src/pybind/mgr/prometheus/module.py
      - src/rgw/driver/rados/rgw_sync_counters.cc
      - src/rgw/rgw_dmclock_scheduler_ctx.cc
      - src/rgw/rgw_perf_counters.cc
      - src/SimpleRADOSStriper.cc
      - src/tools/cephfs_mirror/FSMirror.cc
      - src/tools/cephfs_mirror/Mirror.cc
      - src/tools/cephfs_mirror/PeerReplayer.cc
      - src/tools/rbd_mirror/image_replayer/journal/Replayer.cc
      - src/tools/rbd_mirror/image_replayer/snapshot/Replayer.cc
      - src/tools/rbd_mirror/main.cc
      - src/tools/rbd_mirror/Mirror.cc
